# Generated by Django 4.2.7 on 2023-11-30 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('Password', models.CharField(blank=True, max_length=8)),
                ('Re_Enter_Password', models.CharField(blank=True, max_length=8)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/avatar.png', null=True, upload_to=home.models.unique_name)),
                ('create_at', models.DateField(auto_now=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('delete_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
