# Generated by Django 4.2.7 on 2023-11-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='Re_Enter_Password',
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='is_checked',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
