# Generated by Django 4.2.7 on 2023-12-04 03:24

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_courses_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_img',
        ),
        migrations.AddField(
            model_name='courses',
            name='c_images',
            field=models.ImageField(blank=True, default='profile_pics/avt.png', null=True, upload_to=home.models.unique_name),
        ),
    ]
