# Generated by Django 4.2.7 on 2023-12-04 03:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_courses_c_images_courses_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_img',
            field=models.ImageField(blank=True, default='course/python-fullstack.png', null=True, upload_to=home.models.unique_name),
        ),
    ]
