# Generated by Django 4.2.7 on 2023-12-04 04:18

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_courses_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_img',
            field=models.ImageField(blank=True, default='media/avt.jpg', null=True, upload_to=home.models.unique_name),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/avatar.png', null=True, upload_to=home.models.unique_name),
        ),
    ]
