# Generated by Django 4.2.7 on 2023-12-05 02:21

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_courses_course_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_img',
            field=models.ImageField(blank=True, default='profile_pics/avt.jpg', null=True, upload_to=home.models.unique_name),
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=50)),
                ('lesson_order', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
    ]
