# Generated by Django 4.2.7 on 2023-12-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
