# Generated by Django 4.2.7 on 2023-12-05 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
