# Generated by Django 4.2.7 on 2023-12-06 04:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='course_name', unique=True),
        ),
    ]
