# Generated by Django 4.2.7 on 2023-12-06 05:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_courses_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='news_slug',
        ),
        migrations.AddField(
            model_name='courses',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default='default-slug', editable=False, populate_from='course_name', unique=True),
        ),
    ]
