# Generated by Django 4.2.7 on 2023-12-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_courses_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='slug',
        ),
    ]
