# Generated by Django 4.2.7 on 2023-12-08 09:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='course_name', editable=False, populate_from='course_name', unique=True),
        ),
    ]
