# Generated by Django 4.2.7 on 2023-12-08 09:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=models.CharField(max_length=250), editable=False, populate_from='course_name', unique=True),
        ),
    ]
