# Generated by Django 4.2.7 on 2023-12-13 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0042_alter_reviews_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='course',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='courses',
            field=models.ManyToManyField(to='home.courses'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
