# Generated by Django 4.2.7 on 2023-12-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_reviews_course_remove_reviews_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='courses',
            new_name='course',
        ),
    ]
