# Generated by Django 4.2.7 on 2023-12-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_rename_courses_reviews_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='course',
            new_name='courses',
        ),
    ]
