# Generated by Django 4.2.7 on 2023-12-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_rename_course_reviews_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
