# Generated by Django 4.2.7 on 2023-12-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='course',
            new_name='courses',
        ),
    ]
