# Generated by Django 4.2.7 on 2023-12-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_rename_course_review_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
