# Generated by Django 4.2.7 on 2023-12-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
