# Generated by Django 4.2.7 on 2023-12-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
